
source 'https://cdn.cocoapods.org/'
source 'https://github.com/TuyaInc/TuyaPublicSpecs.git'

platform :ios, '9.0'

target 'TuyaSmartPanelSDK_Example' do
  
   pod 'TuyaSmartDemo', :subspecs => [ "Login", "SmartScene", "DeviceList", "UserInfo" ]
   pod 'TuyaSmartPanelBizBundle'
   # 若需要扫地机功能，请依赖扫地机相关插件
   # pod "TuyaRNApi/Sweeper"

   # 若需要其他版本的 React，可在此添加对应版本的依赖
   # pod 'React'
   # pod 'react-native-maps'
   # pod 'rn-fetch-blob'
   # pod 'RNSVG'
   # pod 'react-native-image-picker'
   # pod 'react-native-video'
   # pod 'RNViewShot'
end
